import { EventsList } from '../components/EventsList';
import { Event } from '../types';

export function Events() {
  // Temporary mock data
  const mockEvents: Event[] = [
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },{
      id: '1',
      title: 'Tech Conference 2024',
      description: 'Annual technology conference',
      date: new Date('2024-06-15'),
      location: 'Convention Center',
      capacity: 500,
      price: 299.99,
      status: 'ongoing',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  return (
    <div>
      <h1 className="text-4xl font-bold text-gray-800 dark:text-gray-200 mb-8">
        Events
      </h1>
      <EventsList 
        events={mockEvents} 
      />
    </div>
  );
}